//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetable.Client.DaysServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DaysServiceReference.IDaysService")]
    public interface IDaysService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaysService/GetAllDays", ReplyAction="http://tempuri.org/IDaysService/GetAllDaysResponse")]
        Timetable.DAL.ViewModels.DayViewModel[] GetAllDays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaysService/GetAllDays", ReplyAction="http://tempuri.org/IDaysService/GetAllDaysResponse")]
        System.Threading.Tasks.Task<Timetable.DAL.ViewModels.DayViewModel[]> GetAllDaysAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDaysServiceChannel : Timetable.Client.DaysServiceReference.IDaysService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DaysServiceClient : System.ServiceModel.ClientBase<Timetable.Client.DaysServiceReference.IDaysService>, Timetable.Client.DaysServiceReference.IDaysService {
        
        public DaysServiceClient() {
        }
        
        public DaysServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DaysServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaysServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaysServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Timetable.DAL.ViewModels.DayViewModel[] GetAllDays() {
            return base.Channel.GetAllDays();
        }
        
        public System.Threading.Tasks.Task<Timetable.DAL.ViewModels.DayViewModel[]> GetAllDaysAsync() {
            return base.Channel.GetAllDaysAsync();
        }
    }
}
