//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetable.Client.DaysServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DaysServiceReference.IDayService")]
    public interface IDayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayService/GetAllDays", ReplyAction="http://tempuri.org/IDayService/GetAllDaysResponse")]
        Timetable.DAL.Model.days[] GetAllDays();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayService/GetAllDays", ReplyAction="http://tempuri.org/IDayService/GetAllDaysResponse")]
        System.Threading.Tasks.Task<Timetable.DAL.Model.days[]> GetAllDaysAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayServiceChannel : Timetable.Client.DaysServiceReference.IDayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayServiceClient : System.ServiceModel.ClientBase<Timetable.Client.DaysServiceReference.IDayService>, Timetable.Client.DaysServiceReference.IDayService {
        
        public DayServiceClient() {
        }
        
        public DayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Timetable.DAL.Model.days[] GetAllDays() {
            return base.Channel.GetAllDays();
        }
        
        public System.Threading.Tasks.Task<Timetable.DAL.Model.days[]> GetAllDaysAsync() {
            return base.Channel.GetAllDaysAsync();
        }
    }
}
