//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Timetable.DAL.ViewModels;

namespace Timetable.Client.HoursServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoursServiceReference.IHoursService")]
    public interface IHoursService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoursService/GetAllHours", ReplyAction="http://tempuri.org/IHoursService/GetAllHoursResponse")]
        HourViewModel[] GetAllHours();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoursService/GetAllHours", ReplyAction="http://tempuri.org/IHoursService/GetAllHoursResponse")]
        System.Threading.Tasks.Task<HourViewModel[]> GetAllHoursAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHoursServiceChannel : Timetable.Client.HoursServiceReference.IHoursService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoursServiceClient : System.ServiceModel.ClientBase<Timetable.Client.HoursServiceReference.IHoursService>, Timetable.Client.HoursServiceReference.IHoursService {
        
        public HoursServiceClient() {
        }
        
        public HoursServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoursServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoursServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoursServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HourViewModel[] GetAllHours() {
            return base.Channel.GetAllHours();
        }
        
        public System.Threading.Tasks.Task<HourViewModel[]> GetAllHoursAsync() {
            return base.Channel.GetAllHoursAsync();
        }
    }
}
